spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecard_db
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

zidtech:
  security:
    jwt:
      secret-key: "{YOUR_SECRET_KEY}"
      access-token-expiry: 900000      # 15 minutes
      refresh-token-expiry: 604800000  # 7 days
      access-token-cookie-name: access_token
      refresh-token-cookie-name: refresh_token